services:
  - type: web
    name: laravel-voting-system
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:3WjtFRQNSZMzRMXSvDg33K958guN24K/hPwPRF4NHaE=
      - key: APP_URL
        value: https://laravel-voting-system.onrender.com
    plan: free

